### ISSUE TITLE
Passwords not accessible offline

### ISSUE THREAD

**Issue by nachadan** [nr23730/nc-passwords-app#1]
Is there any way to access passwords offline? 
I would like to at least copy password when i dont have internet.
Thank you very much for reply

**Comment by nr23730** [comment]
Hi! This is just a fork of the app where I started developing new features. You may want to checkout the original Repository on GitLab here: https://gitlab.com/joleaf/nc-passwords-app/

There is also an issue for offline mode: https://gitlab.com/joleaf/nc-passwords-app/-/issues/81
